### ISSUE TITLE
无法运行polygon数据源示例

### ISSUE THREAD

**Issue by QGB** [klinecharts/pro#6]
https://pro.klinecharts.com/getting-started.html

```
klinecharts-pro.umd.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'registerOverlay')
    at klinecharts-pro.umd.js:1:175612
    at Array.forEach (<anonymous>)
    at klinecharts-pro.umd.js:1:175598
    at klinecharts-pro.umd.js:1:212
    at klinecharts-pro.umd.js:1:251
(匿名) @ klinecharts-pro.umd.js:1
(匿名) @ klinecharts-pro.umd.js:1
(匿名) @ klinecharts-pro.umd.js:1
(匿名) @ klinecharts-pro.umd.js:1
pro.html:23 
        
       Uncaught TypeError: klinechartspro.DefaultDatafeed is not a constructor
    at pro.html:23:15

```

**Comment by liihuu** [comment]
参考 https://github.com/klinecharts/preview

**Comment by saynever2015** [comment]
你好，在html中我也遇到这个问题了，能帮忙看看怎么解决吗

[Sample.txt](https://github.com/klinecharts/pro/files/11589330/Sample.txt)

**Comment by InsectQY** [comment]
有同样的问题，请问解决了吗

**Comment by dareklab** [comment]
有解决的吗？
